module Slkecho
  module SlackRequest
    class LookupUserByEmail
      @slack_api_token: String

      def initialize: (slack_api_token: String) -> void
      def send_request: (String, String) -> untyped
      def uri_with_query: (String, untyped) -> untyped
    end
  end
end
