#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/slkecho"

Slkecho.configure do |config|
  config.slack_api_token = ENV.fetch("SLACK_API_TOKEN", nil)
end

begin
  Slkecho::CLI.run(ARGV)
rescue Slkecho::InvalidOptionError => e
  abort e.message
rescue Slkecho::SlackApiHttpError => e
  abort "Slack API request failed: #{e.message}"
rescue Slkecho::SlackApiResultError => e
  abort "Slack API was responsed with error: #{e.message}"
end
