#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/slkecho"

Slkecho.configure do |config|
  config.slack_api_token = ENV["SLACK_API_TOKEN"]
end

begin
  Slkecho::CLI.run(ARGV)
  puts "Message sent successfully."
rescue Slkecho::InvalidConfigurationError => e
  abort "#{e.message} Please set SLACK_API_TOKEN environment variable." if e.item == :slack_api_token
  abort e.message
rescue Slkecho::InvalidOptionError => e
  abort e.message
rescue Slkecho::SlackApiHttpError => e
  abort "Request failed: #{e.message}"
rescue Slkecho::SlackApiResultError => e
  abort "Error responsed: #{e.message}"
end
